# Generated by Django 5.2.9 on 2025-12-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DomainReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Наприклад: bbc.com, pravda.com.ua",
                        max_length=255,
                        unique=True,
                        verbose_name="Домен",
                    ),
                ),
                (
                    "reputation_type",
                    models.CharField(
                        choices=[
                            ("whitelist", "Білий список (достовірні)"),
                            ("blacklist", "Чорний список (сумнівні)"),
                        ],
                        max_length=20,
                        verbose_name="Тип репутації",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Опис/причина"),
                ),
                (
                    "added_by",
                    models.CharField(blank=True, max_length=100, verbose_name="Додав"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Додано"),
                ),
            ],
            options={
                "verbose_name": "Репутація домену",
                "verbose_name_plural": "Репутації доменів",
                "ordering": ["reputation_type", "domain"],
            },
        ),
        migrations.CreateModel(
            name="NewsCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True, max_length=2048, verbose_name="URL новини"
                    ),
                ),
                (
                    "url_hash",
                    models.CharField(
                        help_text="SHA-256 hash для швидкого пошуку",
                        max_length=64,
                        unique=True,
                        verbose_name="Hash URL",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Заголовок статті"
                    ),
                ),
                (
                    "source_domain",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Домен джерела"
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("pending", "В обробці"),
                            ("true", "Достовірна"),
                            ("false", "Фейк"),
                            ("partial", "Частково правда"),
                            ("unverifiable", "Неможливо перевірити"),
                            ("error", "Помилка обробки"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Вердикт",
                    ),
                ),
                (
                    "is_fake",
                    models.BooleanField(
                        default=False,
                        help_text="True якщо новина визнана фейковою",
                        verbose_name="Є фейком",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0, verbose_name="Рівень впевненості (0-100%)"
                    ),
                ),
                (
                    "ai_verdict_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Структурована відповідь від Gemini API",
                        verbose_name="Повна відповідь AI (JSON)",
                    ),
                ),
                (
                    "ai_response",
                    models.TextField(blank=True, verbose_name="Текстова відповідь AI"),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="ID Celery задачі",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
            ],
            options={
                "verbose_name": "Перевірка новини",
                "verbose_name_plural": "Перевірки новин",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["url_hash"], name="news_newsch_url_has_a82f54_idx"
                    ),
                    models.Index(
                        fields=["task_id"], name="news_newsch_task_id_b930f7_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="news_newsch_created_d7ad6f_idx"
                    ),
                    models.Index(
                        fields=["source_domain"], name="news_newsch_source__4abc27_idx"
                    ),
                    models.Index(
                        fields=["verdict"], name="news_newsch_verdict_38660c_idx"
                    ),
                ],
            },
        ),
    ]
