# Generated by Django 5.1.5 on 2026-05-06 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newscheck",
            name="verdict",
            field=models.CharField(
                choices=[
                    ("pending", "В обробці"),
                    ("fact", "Факт"),
                    ("false-fake", "Фейк"),
                    ("clickbait", "Клікбейт"),
                    ("opinion", "Думка"),
                    ("satire", "Сатира"),
                    ("unverifiable", "Неможливо перевірити"),
                    ("error", "Помилка обробки"),
                    ("true", "Достовірна"),
                    ("false", "Фейк"),
                    ("partial", "Частково правда"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Вердикт",
            ),
        ),
        migrations.CreateModel(
            name="NewsCheckStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage_name",
                    models.CharField(
                        max_length=100, verbose_name="Етап перевірки (STAGE_*)"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        max_length=255, verbose_name="Ім'я файлу (напр. intent_1.md)"
                    ),
                ),
                (
                    "content",
                    models.TextField(verbose_name="Вміст файлу (.md або .json)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "news_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="news.newscheck",
                        verbose_name="Перевірка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Етап перевірки",
                "verbose_name_plural": "Етапи перевірок",
                "ordering": ["created_at"],
            },
        ),
    ]
