# Generated by Django 5.1.5 on 2026-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newscheck_verdict_newscheckstage"),
    ]

    operations = [
        migrations.AddField(
            model_name="newscheck",
            name="pipeline_artifacts",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="Проміжні результати пайплайну (Markdown)",
            ),
        ),
        migrations.DeleteModel(
            name="NewsCheckStage",
        ),
    ]
