# Generated by Django 5.2.14 on 2026-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_newscheck_pipeline_artifacts_delete_newscheckstage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newscheck",
            name="verdict",
            field=models.CharField(
                choices=[
                    ("pending", "В обробці"),
                    ("true", "Достовірна"),
                    ("false", "Фейк"),
                    ("partial", "Частково правда"),
                    ("unverifiable", "Неможливо перевірити"),
                    ("error", "Помилка обробки"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Вердикт",
            ),
        ),
    ]
