# Generated by Django 5.2.14 on 2026-05-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_newscheck_verdict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newscheck",
            name="confidence_score",
        ),
    ]
