# Generated by Django 5.2.14 on 2026-05-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_remove_newscheck_confidence_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newscheck",
            name="verdict",
            field=models.CharField(
                choices=[
                    ("pending", "В обробці"),
                    ("true", "Достовірна"),
                    ("fact", "Факт"),
                    ("false", "Фейк"),
                    ("false-fake", "Фейк"),
                    ("partial", "Частково правда"),
                    ("clickbait", "Клікбейт"),
                    ("opinion", "Думка"),
                    ("satire", "Сатира"),
                    ("unverifiable", "Неможливо перевірити"),
                    ("error", "Помилка обробки"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Вердикт",
            ),
        ),
    ]
