# Generated by Django 5.2.14 on 2026-05-06 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_newscheck_verdict"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParserDebugInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parsed_title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Заголовок (parsed)"
                    ),
                ),
                (
                    "parsed_text",
                    models.TextField(blank=True, verbose_name="Повний текст статті"),
                ),
                (
                    "parsed_authors",
                    models.JSONField(blank=True, default=list, verbose_name="Автори"),
                ),
                (
                    "parsed_publish_date",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Дата публікації (raw)",
                    ),
                ),
                (
                    "parsed_domain",
                    models.CharField(blank=True, max_length=255, verbose_name="Домен"),
                ),
                (
                    "parsed_meta_description",
                    models.TextField(blank=True, verbose_name="Meta Description"),
                ),
                (
                    "parsed_word_count",
                    models.IntegerField(default=0, verbose_name="Кількість слів"),
                ),
                (
                    "parsers_debug",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Порівняння результатів парсерів",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Збережено"),
                ),
                (
                    "news_check",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parser_debug",
                        to="news.newscheck",
                        verbose_name="Перевірка новини",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parser Debug Info",
                "verbose_name_plural": "Parser Debug Info",
            },
        ),
    ]
